name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache cargo data
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Cap'n Proto
      run: sudo apt-get install -y capnproto
    
    - name: Instally Clippy
      run: cargo install clippy

    - name: Build
      run: cargo build --verbose

    - name: Check
      run: cargo clippy --verbose -- -D clippy::all
      
    - name: Run tests
      run: cargo test --verbose
